<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Title>Alura Report Generator</Title>
    <Authors>Professor Vinícius</Authors>
    <Version>1.1.2</Version>
    <Company>Alura</Company>
    <Description>Biblioteca de geração de relatórios </Description>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>ReportGenerator_Alura</PackageId>
    <Version>1.0.1</Version>
    <Authors>Prof Vinícius Costa Santos</Authors>
    <Company>Alura</Company>
    <Description>A library for generating reports in various formats.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/alura-cursos/AluraReportGenerator.git</RepositoryUrl>
    <PackageProjectUrl>https://github.com/alura-cursos/AluraReportGenerator.git</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
